export const tools = [
  {
    image: "/img/js.png",
    name: "JavaScript",
    height: "32",
    width: "28",
  },
  {
    image: "/img/react.png",
    name: "React.js",
    height: "32",
    width: "32",
  },
  {
    image: "/img/next-js.png",
    name: "Next.js",
    height: "32",
    width: "32",
  },
  {
    image: "/img/css3.png",
    name: "CSS",
    height: "32",
    width: "28",
  },
  {
    image: "/img/html5.png",
    name: "HTML",
    height: "32",
    width: "28",
  },
  {
    image: "/img/firebase.png",
    name: "Firebase",
    height: "32",
    width: "32",
  },
  {
    image: "/img/jirasoftware.png",
    name: "JiraSoftware",
    height: "32",
    width: "32",
  },
  {
    image: "/img/figma.png",
    name: "Figma",
    height: "32",
    width: "28",
  },
  {
    image: "/img/adobexd.png",
    name: "AdobeXD",
    height: "32",
    width: "32",
  },
  {
    image: "/img/nodejs.png",
    name: "Node.js",
    height: "32",
    width: "32",
  },
  {
    image: "/img/js.png",
    name: "JavaScript",
    height: "32",
    width: "28",
  },
  {
    image: "/img/react.png",
    name: "React.js",
    height: "32",
    width: "32",
  },
  {
    image: "/img/next-js.png",
    name: "Next.js",
    height: "32",
    width: "32",
  },
  {
    image: "/img/css3.png",
    name: "CSS",
    height: "32",
    width: "28",
  },
  {
    image: "/img/html5.png",
    name: "HTML",
    height: "32",
    width: "28",
  },
  {
    image: "/img/firebase.png",
    name: "Firebase",
    height: "32",
    width: "32",
  },
  {
    image: "/img/jirasoftware.png",
    name: "JiraSoftware",
    height: "32",
    width: "32",
  },
  {
    image: "/img/figma.png",
    name: "Figma",
    height: "32",
    width: "28",
  },
  {
    image: "/img/adobexd.png",
    name: "AdobeXD",
    height: "32",
    width: "32",
  },
  {
    image: "/img/nodejs.png",
    name: "Node.js",
    height: "32",
    width: "32",
  },
];
